import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CartProvider } from "@/context/CartContext";
import CartCount from "@/components/CartCount";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <nav className="bg-white border-b border-gray-100 py-4 px-8 sticky top-0 z-50">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <span className="text-xl font-bold text-gray-900 tracking-tight">PracticeShop</span>
              <div className="flex items-center space-x-2 bg-gray-50 px-4 py-2 rounded-full border border-gray-100">
                <span className="text-sm font-medium text-gray-600">Cart</span>
                <CartCount />
              </div>
            </div>
          </nav>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
