export const challengeNamesData = [
    { name: "Timer", hint: "1. set the time state inside set interval. 2. Convert the total seconds to hours then remaining second to min " },
    { name: "Popover", hint: "subscribe listener then close popover when popover ref does not contains outside target document" },
    { name: "TypeWriterEffect", hint: "Simulates typing text one character at a time" },
    { name: "Calender", hint: "Date picker or calendar UI component" },
    { name: "AllCheckboxes", hint: "Toggle all checkboxes and track their state" },
    { name: "CommentReplyBox", hint: "Nested comment UI with reply functionality" },
    { name: "FolderStructure", hint: "Tree-view folder navigation UI" },
    { name: "FormValidation", hint: "Input validation logic in forms" },
    { name: "HackerNews", hint: "Display stories from Hacker News API" },
    { name: "Carousel", hint: "Image slider or carousel with navigation" },
    { name: "InfiniteReloading", hint: "Scroll to load more data endlessly" },
    { name: "Lights", hint: "Toggle lights on and off, possibly like a puzzle" },
    { name: "Mention", hint: "Typing '@' shows a mention list" },
    { name: "MultiStepper", hint: "Multi-step form with step progress" },
    { name: "Otp", hint: "OTP input with multiple boxes" },
    { name: "Circles", hint: "Animated or interactive circular UI (e.g., loaders)" },
    { name: "ProgressBar", hint: "Horizontal progress bar component" },
    { name: "SnakeLadderBoard", hint: "Board layout for Snake and Ladder game" },
    { name: "Board", hint: "Basic board layout for games or grids" },
    { name: "Timer1", hint: "Alternative timer implementation" },
    { name: "TransferBox", hint: "Move items between two lists" },
];
